---
services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    hostname: traefik
    env_file:
      - path: ./default.env
        required: true
    restart: unless-stopped
    volumes:
      # The configuration directory for traefik
      - ./traefik:/etc/traefik
      # So that Traefik can listen to other Docker Containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # Add health check
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s
    # Very important in order to access the VM
    network_mode: host

  # A container that exposes an API to show its IP address
  whoami:
    image: traefik/whoami
    container_name: whoami
    hostname: whoami
    depends_on:
      traefik:
        condition: service_healthy # Wait for Traefik to be healthy
    labels:
        - traefik.enable=true                                       # To enable whoami to Traefik
        - traefik.http.routers.whoami.rule=Host(`whoami.localhost`) # Declare the host rule for this service
        - traefik.http.routers.whoami.entrypoints=web               # Declare the EntryPoint

